version: '3.8'

services:
  # Frontend Dashboard
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost:8000}
    restart: unless-stopped
    networks:
      - resilibot-network

  # LocalStack for local AWS services (optional for development)
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,dynamodb,s3,cloudwatch,events,apigateway
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - resilibot-network
    profiles:
      - dev

networks:
  resilibot-network:
    driver: bridge
